# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'proyectoCoppel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'youtube-ios-player-helper', '~> 0.1'

  # Pods for proyectoCoppel

  target 'proyectoCoppelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'proyectoCoppelUITests' do
    # Pods for testing
  end

end
